### ISSUE TITLE
Move Git + GitHub introduction doc to lab-guidelines repository

### ISSUE THREAD

**Issue by vladimir-v-diaz** [secure-systems-lab/code-style-guidelines#13]
It's odd to have the Git + GitHub introductory document in the code-style-guidelines repository.
It should instead be moved to the [lab-guidelines repository](https://github.com/secure-systems-lab/lab-guidelines).

**Comment by aaaaalbert** [comment]
Done in secure-systems-lab/lab-guidelines#9, closing this issue.
