### ISSUE TITLE
Avoid trailing whitespaces

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/code-style-guidelines#5]
I recently started using a text editor plugin that unveils trailing white spaces in a funky color. This makes all of our projects look like pieces of modern art. 

We do say that our guidelines are based on `Pep 8` which mentions that one should avoid [trailing white spaces](https://www.python.org/dev/peps/pep-0008/#other-recommendations) for good reasons (other than distracting people with said plugins).

Does anyone care for a tiny addition to the guidelines, encouraging using text editor plugins/options that show  trailing whites paces, and or linters like `flake8` which warn about them? Or should I just stop using my plugin?

**Comment by vladimir-v-diaz** [comment]
I think it's better if we remove any artwork found in the code.

**Comment by aaaaalbert** [comment]
I'm also all for removing trailing whitespace on encounter. However, I'm not so sure about creating a new style rule especially for this....

**Comment by JustinCappos** [comment]
I think your plug-in is helpful.  I don't know we need to require that
people use a plug-in, but suggesting it and reiterating the need to avoid
trailing spaces makes sense to me.

**Comment by lukpueh** [comment]
Just found a neat hidden feature on [GitHub secrets](https://github.com/blog/967-github-secrets).
*"Add **?w=1** to the URL to see the diff with whitespace ignored."*

**Comment by SantiagoTorres** [comment]
Adding to the `git diff` suggestion, git diff can take the --check flag to tell you common errors in your commit code:

```bash
santiago at ~/tuf ✔ git diff --check HEAD^
src/tuf/tests/simple_server.py:4: trailing whitespace.
+ 
src/tuf/tests/simple_server.py:10: trailing whitespace.
+  
src/tuf/tests/simple_server.py:15: trailing whitespace.
+  This is a basic server that was designed to be used in conjunction with 
src/tuf/tests/simple_server.py:16: trailing whitespace.
+  test_download.py to test download.py module. 
src/tuf/tests/test_download.py:19: trailing whitespace.
+Otherwise, module that launches simple server would not be found.  
src/tuf/tests/test_download.py:75: trailing whitespace.
+    self.target_hash = {'md5':digest}  
src/tuf/tests/test_download.py:103: trailing whitespace.
+                      required_hashes=self.target_hash) 
src/tuf/tests/test_download.py:110: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:117: trailing whitespace.
+    self.assertRaises(tuf.DownloadError, 
src/tuf/tests/test_download.py:119: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:122: trailing whitespace.
+    self.assertRaises(tuf.DownloadError, 
src/tuf/tests/test_download.py:124: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:128: trailing whitespace.
+    self.assertRaises(tuf.DownloadError, 
src/tuf/tests/test_download.py:136: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:142: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:148: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:154: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:164: trailing whitespace.
+                      required_hashes=self.target_hash, 
src/tuf/tests/test_download.py:168: trailing whitespace.
+    end_real = time.time()  
```
(This looks better with colored output)

**Comment by lukpueh** [comment]
The newly referenced Google style guide mentions avoiding trailing whitespace, and so does PEP 8. Moreover, linters will easily flag this. I suggest we close the issue with #21.
