### ISSUE TITLE
Git practices / Broadening this repo

### ISSUE THREAD

**Issue by awwad** [secure-systems-lab/code-style-guidelines#6]
We need to either add git practices to the existing code style guidelines document, add a document for git practices, or repurpose a contributing-to-lab-projects document (Seattle has one [here](https://seattle.poly.edu/wiki/ContributorsPage), and a fledgling modernization [here](https://github.com/SeattleTestbed/docs/tree/master/Contributing).).

Among the things to cover in such a document:
- Commit message practices. [This](https://chris.beams.io/posts/git-commit/) is a good guide. (I'm still refining my own practices along these lines. (: )
- Branching guidelines
- Contribution guidelines, e.g. forking & send pull request. (At least a few people have been pretty confused by this.) Seattle's contributor portal links to [this page on this subject](https://seattle.poly.edu/wiki/Local/RepoAccess).

I know that @lukpueh at least has mentioned lab guidelines / introduction documents. Perhaps this repository should host a wiki covering these things, with the code style guidelines just being one piece of it.

**Comment by vladimir-v-diaz** [comment]
> Contribution guidelines, e.g. forking & send pull request. (At least a few people have been pretty confused by this.)

We have a guide to using Git and GitHub (https://seattle.poly.edu/wiki/Local/RepoAccess), but it hasn't been moved over to this repository.

**Comment by awwad** [comment]
Oh, I didn't catch that one. Not bad! Edited original post to include it beside the general link.

**Comment by SantiagoTorres** [comment]
Speaking of which. I don't know if this may be tangential to this issue, but [what about adding issue and PR templates](https://github.com/blog/2111-issue-and-pull-request-templates) so students can get an idea of what should be in here?

**Comment by aaaaalbert** [comment]
@vladimir-v-diaz, there's also a Markdown rendition of the guide: https://github.com/SeattleTestbed/docs/blob/master/Archive/Local/RepoAccess.md

The screenshots were gitified, but never added back into the text: https://github.com/SeattleTestbed/docs/tree/master/ATTACHMENTS/Local/RepoAccess

**Comment by aaaaalbert** [comment]
I think this is addressed by the (still pending) PR secure-systems-lab/lab-guidelines#4. The Git/GitHub guide mentioned above just became a lab guideline via secure-systems-lab/lab-guidelines#9.

I vote to close this issue.

**Comment by lukpueh** [comment]
Fixed by the introduction of a development guidelines document in secure-systems-lab/lab-guidelines#4.
